local:
	eval $(minikube docker-env)
	docker build ./ -t  stats
	docker run -p 5000:5000 stats

dockerrepo:
	eval $(minikube docker-env)
	docker tag stats janotijr/stats
	docker build ./ -t janotijr/stats
	docker push janotijr/devops-project:stats

k8s:
	eval $(minikube docker-env)
	minikube start --vm-driver=virtualbox
	kubectl apply -f deployment.yaml
	http://192.168.99.100:31279




help:
	@echo ''
	@echo '  local                 build docker --image-- local'
	@echo '  dockerrepo    	build docker --image-- for janotijr in Docker Hub public repo. Might run $ docker login first'
	@echo '  k8s		        buil a local kubernetes cluster with minikube'
