---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: application
  name: stats-k8s
spec:
  selector:
    matchLabels:
      app: stats
  replicas: 4
  template:
    metadata:
      labels:
        app: stats
    spec:
      containers:
      - name: stats
        imagePullPolicy: Always
        image: janotijr/devops-project-1:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 4m
          requests:
            cpu: 4m
---
apiVersion: v1
kind: Service
metadata:
  namespace: application
  labels:
    app: stats
  name: stats-k8s
spec:
  selector:
    app: stats
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: NodePort

  